#ifndef SRC3_APP_NERTC_CALL_H
#define SRC3_APP_NERTC_CALL_H

#define ACTION_NERTC_CALL_MAIN  0x00009001

typedef enum {
    APP_NERTC_CALL_STATE_STARTING = 0,
    APP_NERTC_CALL_STATE_IDLE,
    APP_NERTC_CALL_STATE_LISTENING,
    APP_NERTC_CALL_STATE_SPEAKING,
} app_nertc_call_state_t;

#endif
